#spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
#spring.datasource.url: jdbc:mysql://localhost:3306/shop_online?serverTimezone=Asia/Shanghai
#spring.datasource.username: root
#spring.datasource.password: root

#mybatis.mapper-locations: classpath:mappers/*Mapper.xml
#mybatis.type-aliases-package: com.example.backend.entity.bean
#
#server.servlet.context-path: /shop_online
#server.port: 8080

spring:
  security:
    jwt:
      key: abcdef
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3306/shop_online
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#    security:
#      user:
#        name: root
#        password: root

